#! /bin/sh

bspc monitor DisplayPort-4 -d I II III
bspc monitor DVI-D-1 -d IV V VI VII
bspc monitor HDMI-A-1 -d VIII IX X

bspc config border_width             0
bspc config window_gap              24

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer true
